project_id = "ftgcbmthbwwcumvqnuof"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-contact-email]
verify_jwt = false

[functions.send-tryout-email]
verify_jwt = false

[functions.send-membership-application]
verify_jwt = false
